tap "homebrew/cask"
cask_args appdir: "/Applications"

brew "imagemagick"
brew "azure-cli"
brew "curl"
brew "git"
brew "go"
brew "godep"
brew "kubeless"
brew "serverless"
brew "kubernetes-cli"
brew "kubernetes-helm"
brew "minio/stable/mc"
brew "node"
brew "openssl"
brew "python"
brew "watch"
brew "wget"
brew "python"
brew "pipenv"
brew "cython"
brew "geckodriver"
brew "bash-completion"

cask "google-chrome"
cask "chromedriver"
cask "firefox"
cask "mattermost"
cask "dotnet-sdk"
cask "docker"
cask "visual-studio-code"
cask "pycharm-ce"
cask "xquartz"
cask "microsoft-office"
